spring:
  application:
    name: shortlink-demo
  redis:
    database: 6
    host: host
    port: 6379
    password: password
    lettuce:
      pool:
        max-active: 10  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms    # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 5      # 连接池中的最大空闲连接
        min-idle: 2       # 连接池中的最小空闲连接
  datasource:
    url: jdbc:mysql://dev-ip:port/shortlink?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #初始化大小
      initial-size: 5
      #最小连接数
      min-idle: 10
      #最大连接数
      max-active: 20
      #获取连接时的最大等待时间
      max-wait: 60000
      #一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 多久才进行一次检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置扩展插件：stat-监控统计，log4j-日志，wall-防火墙（防止SQL注入），去掉后，监控界面的sql无法统计
      filters: stat,wall,log4j2
      #配置慢sql展示语句   slowSqlMillis 对应的是慢sql的时间
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=10
server:
  port: 8080
mybatis:
  configuration:
    map-underscore-to-camel-case: true #自动驼峰映射
config:
  server: http://127.0.0.1:8080/